# Generated by Django 2.2.6 on 2021-02-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('surname', models.CharField(max_length=24)),
                ('description', models.TextField()),
            ],
        ),
    ]
